### ISSUE TITLE
Add Parameter “replicate” for setting guid_schema and kafka_schema

### ISSUE THREAD

**Issue by danielLinke** [cloudant-labs/kafka-connect-cloudant#23]
Add a new parameter “replicate” in the file connect-cloudant-sink.properties. The property handle the schema of the objects in the sink database. The new attribute “replicate” handle and replace the attributes guid_schema and kafka_schema. 

If the property true the source object should be mirrored in the sink database. Therefore, the system using the guid_schema from the source object and don’t add the kafka_schema to the object.

If the property false the source object should be saved with additional information in the sink database. Therefore, the system create a new object id from kafka (#8) and add the kafka_schema from the SinkRecord (#9).

**Comment by HolgerKache** [comment]
Merged.
