### ISSUE TITLE
Message filters and formats

### ISSUE THREAD

**Issue by HolgerKache** [cloudant-labs/kafka-connect-cloudant#5]
What options do I have to pass a filter or map to decide what messages to accept and what format to accept them in? I know we talked about that but forgot if this was already available to developers today or planned for a future Kafka release.

**Comment by HolgerKache** [comment]
_David Tucker <david@confluent.io>_:

In terms of filtering, the current framework allows you to implement almost anything you like.   You'll see some connectors that support regexp filters for given fields within the record.   The Connect team is working on an abstraction we call "Single Message Transforms" to support a standard way of doing that across connectors; that will be available next year.   The team at DataMountaineer (http://docs.datamountaineer.com/en/latest/connectors.html#connectors) has a very powerful SQL-like model for filtering that may give you some ideas.

**Comment by ricellis** [comment]
Closing, SMTs are available to do this.
