### ISSUE TITLE
SourceTask should only create _running once

### ISSUE THREAD

**Issue by dbtucker** [cloudant-labs/kafka-connect-cloudant#6]
The low-level use of AtomicBooleans to ensure that "poll()" does not conflict with "stop()" is fine, but you'll want to pull the creation of _running into the start() method (along with the creation of stop).   The poll() method can be called literally hundreds of times per second, so you don't want to be wasting time with object creation and garbage collection.

**Comment by asarantes** [comment]
Added and tested code to do that.
