### ISSUE TITLE
Update configuration & validation

### ISSUE THREAD

**Issue by ricellis** [cloudant-labs/kafka-connect-cloudant#61]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Feature Description

We need to update the properties used for configuration to match those available in the new client (`cloudant.url` and friends).

Further as described in [Connect Configuration Validation](https://kafka.apache.org/documentation/#connect_development) we should utilize the validation and recommendation hooks. So for each [`ConfigDef`](https://kafka.apache.org/31/javadoc/org/apache/kafka/common/config/ConfigDef.html):
    * the dependencies should be set (e.g. `cloudant.password` depends on `cloudant.username` and they depend on some specific auth types `cloudant.auth.type=basic|couchdbsession`). An implementation of [`Recommender`](https://kafka.apache.org/31/javadoc/org/apache/kafka/common/config/ConfigDef.Recommender.html) should be added to provide this help to the user.
    * As described in  we should override the [`Validator`](https://kafka.apache.org/31/javadoc/org/apache/kafka/common/config/ConfigDef.Validator.html) class in the `ConfigDef` to provide option validation.

With that information present in the `ConfigDef` I think the default implementation of [`validate()`](https://kafka.apache.org/31/javadoc/org/apache/kafka/common/config/ConfigDef.html#validate(java.util.Map)) will likely be sufficient for our needs (i.e. I don't currently see a need for us to override and automatically set recommended values).

Since a lot of that will be duplicated between source and sink for all the common options of client config we should move those options to a common function that can be shared.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

Currently config validation happens in a few different places:
https://github.com/cloudant-labs/kafka-connect-cloudant/blob/61e0e691fe6a887c5cdc76f1e557221a71dc43cd/src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceConnector.java#L84
https://github.com/cloudant-labs/kafka-connect-cloudant/blob/61e0e691fe6a887c5cdc76f1e557221a71dc43cd/src/main/java/com/ibm/cloudant/kafka/connect/CloudantSourceTask.java#L187

and we lack any real validation of properties.

### 2. What you expected to happen

Properties to be validated using standard Kafka Connect approach.

### 3. What actually happened

No real validation of properties before connector failure.

**Comment by tomblench** [comment]
NB work for this and follow-on tickets will merge to feature branch [feature/61-configuration-validation](https://github.com/cloudant-labs/kafka-connect-cloudant/tree/feature/61-configuration-validation)

**Comment by tomblench** [comment]
PR merged: https://github.com/cloudant-labs/kafka-connect-cloudant/pull/70

Closing
