### ISSUE TITLE
Stop removing `_rev` from sink documents

### ISSUE THREAD

**Issue by ricellis** [cloudant-labs/kafka-connect-cloudant#72]
Currently the sink connector removes the `_rev` field from message values. This is really only relevant if the source information is also another Cloudant or Couch instance and in those cases it probably makes sense to _preserve_ `_rev` information since it has meaning in those systems.

Actions:
- [ ] Delete the line that does the removal https://github.com/cloudant-labs/kafka-connect-cloudant/blob/4964afc739b499898771e2713b44ea140449daab/src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkTask.java#L68
- [ ] document the behaviour
- [ ] document the use of SMT to remove `_rev` information if desired
- [ ] document that the Cloudant sink [currently] will only inserts a single revision of any `_id` (i.e. it cannot do updates or deletes)

**Comment by emlaver** [comment]
As I'm running through some test scenarios, I've tried to pass a document with a rev:
```
echo '{"_id":"2xxx123abc","_rev":"1-15f65339921e497348be384867bb940f","hello":"new1world"}'  | ./bin/kafka-console-producer.sh --topic kafka_test --bootstrap-server localhost:9092 -
```
The document isn't created which is expected.  There's no logging under INFO or DEBUG that let's the user know that the document was not created.  All I see is:
1) pending sink record `Thread[70].sinkRecords = 1 (com.ibm.cloudant.kafka.connect.CloudantSinkTask:62)`
2) Debug showing output stream flushed `Flushing output stream for {https:///}`
3) Committed 1 document which feels misleading `Committed 1 documents to -> https://...`
4) Sink records thread back to 0 `Thread[70].sinkRecords = 0`
