### ISSUE TITLE
Improvement : archive schema from SinkRecord when available

### ISSUE THREAD

**Issue by dbtucker** [cloudant-labs/kafka-connect-cloudant#9]
The schema information from the SinkRecord (it it exists) is discarded.   Not sure if there's any reason to keep those details around as you write the JSON record into Cloudant, but this behavior should be documented regardless.

Alternatively, the schema for a record could be saved to the database with a related _id value (eg <id_record>_kcschema).

**Comment by danielLinke** [comment]
If the property "replication" is false, the schema information from the SinkRecord are saved in the attribute kcschema

**Comment by ricellis** [comment]
Looks like this was fixed in #25 with the `replication` property.
